name: simple-action
on: push
jobs:
 my-job: 
  runs-on: ubuntu-latest
  steps:
    - name:  set-up Python  
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
        run: python my_script.py
